name: Continuous Integration

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: macos-11
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3

      - name: Install Dependencies
        run: |
          pip install -r dev-requirements.txt
        working-directory: ./

      - name: Run Tests
        run: |
          python -m pytest test_edge.py
          python -m pytest test_graphs.py
          python -m pytest test_states.py
        working-directory: ./tests
